# Redirects for BB 2.7
[[redirects]]
from = "https://docs.wpbeaverbuilder.com/beaver-builder/layouts/responsive-design/responsive-behavior-in-beaver-builder"
to = "https://docs.wpbeaverbuilder.com/beaver-builder/layouts/responsive-design"
status = 301
force = true
[[redirects]]
from = "https://docs.wpbeaverbuilder.com/beaver-builder/layouts/responsive-design/responsive-settings-icon"
to = "https://docs.wpbeaverbuilder.com/beaver-builder/layouts/responsive-design/toggle"
status = 301
force = true
[[redirects]]
from = "https://docs.wpbeaverbuilder.com/beaver-builder/layouts/responsive-design/responsive-editing-with-beaver-builder"
to = "https://docs.wpbeaverbuilder.com/beaver-builder/layouts/responsive-design/editor"
status = 301
force = true
[[redirects]]
from = "https://docs.wpbeaverbuilder.com/beaver-builder/layouts/responsive-design/breakpoints-for-device-sizes"
to = "https://docs.wpbeaverbuilder.com/beaver-builder/layouts/responsive-design"
status = 301
force = true
[[redirects]]
from = "https://docs.wpbeaverbuilder.com/beaver-builder/layouts/responsive-design/change-device-breakpoints-site-wide"
to = "https://docs.wpbeaverbuilder.com/beaver-builder/layouts/responsive-design"
status = 301
force = true
[[redirects]]
from = "https://docs.wpbeaverbuilder.com/beaver-builder/layouts/advanced-tab-rows-columns-modules"
to = "https://docs.wpbeaverbuilder.com/beaver-builder/layouts/advanced-tab"
status = 301
force = true
[[redirects]]
from = "https://docs.wpbeaverbuilder.com/beaver-builder/layouts/margins-padding/margin-padding"
to = "https://docs.wpbeaverbuilder.com/beaver-builder/layouts/advanced-tab/spacing"
status = 301
force = true
[[redirects]]
from = "https://docs.wpbeaverbuilder.com/beaver-builder/layouts/margins-padding/change-individual-margin-and-padding-settings"
to = "https://docs.wpbeaverbuilder.com/beaver-builder/layouts/advanced-tab/spacing"
status = 301
force = true
[[redirects]]
from = "https://docs.wpbeaverbuilder.com/beaver-builder/layouts/margins-padding/change-default-row-and-module-margins-and-padding"
to = "https://docs.wpbeaverbuilder.com/beaver-builder/getting-started/bb-editor-basics/global-settings#rows"
status = 301
force = true
[[redirects]]
from = "https://docs.wpbeaverbuilder.com/beaver-builder/layouts/margins-padding/disable-auto-spacing-on-mobile-devices"
to = "https://docs.wpbeaverbuilder.com/beaver-builder/getting-started/bb-editor-basics/global-settings#auto-spacing"
status = 301
force = true
[[redirects]]
from = "https://docs.wpbeaverbuilder.com/beaver-builder/layouts/margins-padding/troubleshooting-margins-and-padding"
to = "https://docs.wpbeaverbuilder.com/beaver-builder/layouts/advanced-tab/spacing"
status = 301
force = true
[[redirects]]
from = "https://docs.wpbeaverbuilder.com/beaver-builder/layouts/columns/prevent-column-stacking-with-custom-widths"
to = "https://docs.wpbeaverbuilder.com/beaver-builder/layouts/columns/stacking"
status = 301
force = true
[[redirects]]
from = "https://docs.wpbeaverbuilder.com/beaver-builder/layouts/columns/reverse-column-stacking-order"
to = "https://docs.wpbeaverbuilder.com/beaver-builder/layouts/columns/stacking"
status = 301
force = true
[[redirects]]
from = "https://docs.wpbeaverbuilder.com/beaver-builder/layouts/templates/export-and-import-saved-templates-rows-columns-modules"
to = "https://docs.wpbeaverbuilder.com/beaver-builder/layouts/templates/export-import-content"
status = 301
force = true

# Custom Module Redirects
[[redirects]]
from = "https://docs.wpbeaverbuilder.com/beaver-builder/developer/custom-modules/cmdg-01-create-a-plugin"
to = "https://docs.wpbeaverbuilder.com/beaver-builder/developer/custom-modules/01-create-a-plugin"
status = 301
force = true


"beaver-builder/developer/custom-modules/02-add-a-module-to-your-plugin",
"beaver-builder/developer/custom-modules/03-define-module-settings",
"beaver-builder/developer/custom-modules/04-module-settings-css-javascript",
"beaver-builder/developer/custom-modules/05-module-html",
"beaver-builder/developer/custom-modules/06-module-css",
"beaver-builder/developer/custom-modules/07-module-javascript",
"beaver-builder/developer/custom-modules/08-module-property-reference",
"beaver-builder/developer/custom-modules/09-module-method-reference",
"beaver-builder/developer/custom-modules/10-setting-fields-reference",
"beaver-builder/developer/custom-modules/11-responsive-fields-reference",
"beaver-builder/developer/custom-modules/12-repeater-fields-reference",
"beaver-builder/developer/custom-modules/13-sanitize-field-values",
"beaver-builder/developer/custom-modules/14-create-custom-fields",
"beaver-builder/developer/custom-modules/15-helpers",
"beaver-builder/developer/custom-modules/16-live-preview-reference",
"beaver-builder/developer/custom-modules/17-partial-refresh-reference",
"beaver-builder/developer/custom-modules/18-override-modules",
"beaver-builder/developer/custom-modules/19-localization",

# Redirect Contact Form module doc link
[[redirects]]
from = "https://docs.wpbeaverbuilder.com/beaver-builder/how-to-tips/use-smtp-to-send-form-notifications"
to = "https://docs.wpbeaverbuilder.com/beaver-builder/troubleshooting/common-issues/use-smtp-to-send-form-notifications"
status = 301
force = true

# Redirect Hooks
[[redirects]]
from = "https://docs.wpbeaverbuilder.com/beaver-builder/developer/tutorials-guides/common-beaver-builder-filter-examples"
to = "https://docs.wpbeaverbuilder.com/beaver-builder/developer/tutorials-guides/common-beaver-builder-plugin-filter-examples"
status = 301
force = true

# Redirect from deleted text editor tips article to Text Editor article
[[redirects]]
from = "https://docs.wpbeaverbuilder.com/beaver-builder/layouts/modules/text-editor/change-fonts-and-colors-in-the-text-editor-module"
to = "https://docs.wpbeaverbuilder.com/beaver-builder/layouts/modules/text"
status = 301
force = true

# Redirect from deleted text editor category to standalone Text Editor article
[[redirects]]
from = "https://docs.wpbeaverbuilder.com/beaver-builder/layouts/modules/text-editor/text"
to = "https://docs.wpbeaverbuilder.com/beaver-builder/layouts/modules/text"
status = 301
force = true

# Home page
[[redirects]]
from = "https://kb.wpbeaverbuilder.com"
to = "https://docs.wpbeaverbuilder.com"
status = 301
force = true
[[redirects]]
from = "http://kb.wpbeaverbuilder.com"
to = "https://docs.wpbeaverbuilder.com"
status = 301
force = true

[[plugins]]
package = "netlify-plugin-image-optim"
