name: Verify Build

on: push

jobs:
  verify-build:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: 16.14
    - name: yarn install
      run: |
        yarn install
    - name: Build
      run: yarn build
