name: Doc Scraper
on:
  schedule:
    - cron: '0 0 * * 0'
jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
    - name: scrape
      uses: wei/curl@master
      with:
        args: ${{ secrets.DOCS_CRAWL }}
